Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 30

Description: Simple example demonstrating a serverless, Rust-powered API implementation.

Resources:
  GetHelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: bootstrap.is.real.handler
      Runtime: provided
      MemorySize: 512
      CodeUri: .
      Events:
        Api:
          Type: Api
          Properties:
            Path: /hello
            Method: get
    Metadata:
      BuildMethod: makefile
